steps:
  # Step 1: Build dell'immagine Docker
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/trading-ai-repo/trading-ai-service:latest", "."]

  # Step 2: Push dell'immagine nel Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/$PROJECT_ID/trading-ai-repo/trading-ai-service:latest"]

  # Step 3: Deploy su Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "trading-ai-service"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/trading-ai-repo/trading-ai-service:latest"
      - "--region=$_REGION"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/trading-ai-repo/trading-ai-service:latest"

substitutions:
  _PROJECT_ID: "trading90"
  _REGION: "us-central1"
