# 📌 Questo workflow esegue il build di un container Docker,
#    lo invia a Google Artifact Registry e lo deploya su Cloud Run.
#
# 🔹 Trigger:
#    - Push su `main` → Deploy in Produzione
#    - Push su `dev` → Deploy in Ambiente di Test
#
# 📌 Prerequisiti:
# 1️⃣ Abilita le API necessarie su Google Cloud:
#    gcloud services enable artifactregistry.googleapis.com run.googleapis.com iamcredentials.googleapis.com cloudbuild.googleapis.com
#
# 2️⃣ Configura il Workload Identity Provider per GitHub Actions:
#    - Segui: https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation
#    - Assegna i ruoli necessari al Service Account:
#      roles/artifactregistry.admin, roles/run.admin, roles/cloudbuild.builds.editor
#
name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main
      - dev

env:
  PROJECT_ID: 'trading90'  # ID del progetto Google Cloud
  REGION: 'us-central1'  # Regione per Cloud Run e Artifact Registry
  SERVICE: 'trading-ai-service'  # Nome del servizio Cloud Run
  REPOSITORY: 'trading-ai-repo'  # Nome del repository Artifact Registry
  WORKLOAD_IDENTITY_PROVIDER: 'projects/945635315103/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}  # Riconosce se è `main` o `dev`

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Necessario per autenticazione Google Cloud

    steps:
      # 🔹 1️⃣ Scarica il codice del repository
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # 🔹 2️⃣ Autenticazione con Google Cloud tramite Workload Identity Federation
      - id: auth
        name: 'Autenticazione su Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-actions@trading90.iam.gserviceaccount.com'

      # 🔹 3️⃣ Configura Docker per autenticarsi su Google Artifact Registry
      - name: 'Docker Authentication'
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # 🔹 4️⃣ Costruisce e carica l'immagine Docker su Google Artifact Registry
      - name: 'Build e Push Docker Image'
        run: |
          IMAGE_TAG="${{ github.sha }}"  # Usa l'hash del commit come tag dell'immagine
          IMAGE_NAME="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${IMAGE_TAG}"
          
          echo "🚀 Costruzione dell'immagine Docker: $IMAGE_NAME"
          docker build --tag "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"
          echo "✅ Immagine Docker caricata: $IMAGE_NAME"

      # 🔹 5️⃣ Esegue il deploy dell'immagine su Cloud Run
      - name: 'Deploy su Cloud Run'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "${{ env.SERVICE }}-${{ env.ENVIRONMENT }}"  # Nome del servizio per ambiente Dev/Prod
          region: ${{ env.REGION }}
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          flags: "--platform managed --allow-unauthenticated"  # Permette accesso pubblico all'API (può essere rimosso per maggiore sicurezza)

      # 🔹 6️⃣ Mostra l'URL del servizio dopo il deploy
      - name: 'Mostra URL del Servizio'
        run: |
          echo "✅ Deploy completato con successo!"
          echo "🌍 Cloud Run URL: ${{ steps.deploy.outputs.url }}"

