name: 'Build and Deploy using deploy.sh'

on:
  push:
    branches:
      - main
      - dev

env:
  PROJECT_ID: 'trading90'  # ID del progetto Google Cloud
  REGION: 'us-central1'  # Regione per Cloud Run e Artifact Registry
  SERVICE: 'trading-ai-service'  # Nome del servizio Cloud Run
  REPOSITORY: 'trading-ai-repo'  # Nome del repository Artifact Registry
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}  # Riconosce se è `main` o `dev`

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Necessario per autenticazione Google Cloud

    steps:
      # 🔹 1️⃣ Scarica il codice del repository
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # 🔹 2️⃣ Autenticazione con Google Cloud utilizzando GitHub Secret
      - id: auth
        name: 'Autenticazione su Google Cloud'
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # 🔹 3️⃣ Rendi eseguibile lo script deploy.sh
      - name: 'Rendi eseguibile deploy.sh'
        run: chmod +x deploy.sh

      # 🔹 4️⃣ Esegui deploy.sh e salva log
      - name: 'Esegui deploy.sh e salva log'
        run: |
          mkdir -p /home/don/trading-ai/.github/log
          ./deploy.sh | tee /home/don/trading-ai/.github/log/github-actions-log.txt

