# This workflow builds a Docker container, pushes it to Google Artifact Registry,
# and deploys it to Cloud Run when a commit is pushed to the "main" branch.
#
# Prerequisites:
#
# 1. Enable the following Google Cloud APIs:
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Cloud Run (run.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#    - Cloud Build API (cloudbuild.googleapis.com)
#
#    Enable them using:
#    gcloud services enable artifactregistry.googleapis.com run.googleapis.com iamcredentials.googleapis.com cloudbuild.googleapis.com
#
# 2. Create and configure a Workload Identity Provider for GitHub Actions:
#    - Follow instructions: https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation
#    - Assign necessary IAM roles to the service account:
#      - Artifact Registry Administrator (roles/artifactregistry.admin)
#      - Cloud Run Developer (roles/run.developer)
#      - Cloud Build Editor (roles/cloudbuild.builds.editor)
#
# 3. Update the "env" variables below to match your project settings.

name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main  # This workflow runs when pushing to "main" branch

env:
  PROJECT_ID: 'trading90' # Google Cloud project ID
  REGION: 'us-central1' # Region for Cloud Run and Artifact Registry
  SERVICE: 'trading-ai-service' # Cloud Run service name
  REPOSITORY: 'trading-ai-repo' # Artifact Registry repository name
  WORKLOAD_IDENTITY_PROVIDER: 'projects/945635315103/locations/global/workloadIdentityPools/github-pool/providers/github-provider' # Workload Identity Provider ID

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required to read repository contents
      id-token: write # Required for Workload Identity Federation authentication

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4 # Retrieves the latest repository code

      # Authenticate with Google Cloud using Workload Identity Federation
      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-actions@trading90.iam.gserviceaccount.com' # Service Account for GitHub Actions

      # Authenticate Docker to push images to Google Artifact Registry
      - name: 'Docker Authentication'
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Build and Push Docker Image to Google Artifact Registry
      - name: 'Build and Push Container'
        run: |
          IMAGE_NAME="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"

      # Deploy the container image to Cloud Run
      - name: 'Deploy to Cloud Run'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

      # Output the Cloud Run service URL
      - name: 'Show Cloud Run URL'
        run: echo "Cloud Run URL: ${{ steps.deploy.outputs.url }}"

